id: P009534
initial_creation_type: ocr
source_metadata:
  id: bdr:W8LS18964
  title: 'ཡུམ་གསུམ་གནོད་འཇོམས། '
  author: ''
  volumes:
    28be50e563474776ab6256738421991c:
      image_group_id: I8LS18966
      title: ''
      volume_number: 1
      total_pages: 544
