id: I6C2768C8
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-28T18:14:24+00:00'
last_modified: '2022-06-08T11:42:43.364545+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W8LS18964
  title: 'ཡུམ་གསུམ་གནོད་འཇོམས། '
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    5AC0:
      image_group_id: I8LS18966
      title: ''
      total_pages: 544
      order: 1
      base_file: 5AC0.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
